services:
  frontend:
    build: ./frontend
    ports:
    - "8000:8000"
    networks:
    - week3
    volumes:
    - ./frontend:/app
    - /app/.venv

  backend:
    build: ./backend
    ports:
    - "8001:8000"
    networks:
    - week3
    volumes:
    - ./backend:/app
    - /app/.venv
    environment:
    - OLLAMA_HOST=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  week3:
    driver: bridge
